name: just_audio_web
description: Web platform implementation of just_audio. This implementation is endorsed and therefore doesn't require a direct dependency.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_web
version: 0.4.9
publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JustAudioPlugin
        fileName: just_audio_web.dart

dependencies:
  just_audio_platform_interface:
    git:
      url: https://github.com/apps-vr/just_audio_enhanced.git
      ref: 0.9.41
      path: just_audio_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
